<?php

namespace App\Imports;

use App\Models\BreakdownLog;
use App\Models\MasterUnit;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithStartRow;

class BreakdownLogsImport implements ToCollection, WithStartRow
{
    /**
     * Start reading from row 4 to skip the heavily styled multi-layer heading array.
     */
    public function startRow(): int
    {
        return 4;
    }

    public function collection(Collection $rows)
    {
        foreach ($rows as $row) {
            // Mapping against the standard format generated by `AllDataBreakdownSheet.php`
            // $row[1]: Vendor (ignored/used inherently by Unit mapping)
            // $row[2]: Unit (Nomor Lambung) -- Primary identifier
            // $row[3]: Keterangan
            // $row[4]: Waktu Breakdown (Awal) -> d M Y H.i
            // $row[5]: Waktu Breakdown (Akhir) -> d M Y H.i or '-'
            // $row[6]: Spare (Unit)
            // $row[7]: Spare Jam Datang -> d M Y H.i or '-'
            // $row[8]: Loss time interval (calculated dynamically automatically)
            // $row[9]: % (calculated automatically)
            // $row[10]: Status (calculated automatically)
            
            $unitNomor = trim((string)($row[2] ?? ''));
            if (!$unitNomor) {
                continue; // Skip silently if core ident is empty
            }

            // Bind master unit forcefully
            $unit = MasterUnit::where('nomor_lambung', $unitNomor)->first();
            if (!$unit) {
                continue; 
            }

            $waktuAwalStr = trim((string)($row[4] ?? ''));
            if (!$waktuAwalStr) {
                continue; 
            }

            try {
                $waktuAwal = $this->parseDate($waktuAwalStr);
                if (!$waktuAwal) continue;

                $waktuAkhirStr = trim((string)($row[5] ?? '-'));
                $waktuAkhir = ($waktuAkhirStr !== '-' && $waktuAkhirStr !== '') ? $this->parseDate($waktuAkhirStr) : null;

                $waktuDatangStr = trim((string)($row[7] ?? '-'));
                $waktuDatang = ($waktuDatangStr !== '-' && $waktuDatangStr !== '') ? $this->parseDate($waktuDatangStr) : null;

                $spareUnitNomor = trim((string)($row[6] ?? '-'));
                $spareUnitId = null;
                if ($spareUnitNomor !== '-' && $spareUnitNomor !== '') {
                    $spareUnit = MasterUnit::where('nomor_lambung', $spareUnitNomor)->first();
                    $spareUnitId = $spareUnit ? $spareUnit->id : null;
                }

                $keterangan = trim((string)($row[3] ?? ''));

                BreakdownLog::create([
                    'unit_id' => $unit->id,
                    'vendor_id' => $unit->vendor_id, 
                    'user_id' => auth()->id() ?? 1,
                    'waktu_awal_bd' => $waktuAwal,
                    'waktu_akhir_bd' => $waktuAkhir,
                    'spare_unit_id' => $spareUnitId,
                    'waktu_spare_datang' => $waktuDatang,
                    'keterangan' => $keterangan,
                ]);

            } catch (\Exception $e) {
                // Trap formatting chaos and glide over to the next row robustly
                continue;
            }
        }
    }

    /**
     * Safely transpile Excel's variant proprietary date payloads or pure strings into eloquent Carbons
     */
    private function parseDate($value)
    {
        if (empty($value)) return null;

        // Maatwebsite raw native numeric representation
        if (is_numeric($value)) {
            return Carbon::instance(\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($value));
        }
        
        try {
            // Translate the "d M Y H.i" legacy export format output (e.g. 24 Mar 2026 14.30)
            $str = str_replace('.', ':', $value);
            return Carbon::createFromFormat('d M Y H:i', $str);
        } catch (\Exception $e) {
            try {
                // Final standard explicit fallback
                return Carbon::parse($value);
            } catch (\Exception $e2) {
                return null;
            }
        }
    }
}
