<?php

namespace App\Imports;

use App\Models\BreakdownLog;
use App\Models\MasterUnit;
use App\Models\Vendor;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithStartRow;
use Illuminate\Support\Facades\Log;

class BreakdownLogsImport implements ToCollection, WithStartRow
{
    public $importedCount = 0;
    public $updatedCount = 0;
    public $skippedCount = 0;
    public $skippedReasons = [];

    /**
     * Start reading from row 4 to skip the heavily styled multi-layer heading array.
     */
    public function startRow(): int
    {
        return 4;
    }

    public function collection(Collection $rows)
    {
        foreach ($rows as $row) {
            // Mapping against the standard format generated by `AllDataBreakdownSheet.php`
            // $row[1]: Vendor (ignored/used inherently by Unit mapping)
            // $row[2]: Unit (Nomor Lambung) -- Primary identifier
            // $row[3]: Keterangan
            // $row[4]: Waktu Breakdown (Awal) -> d M Y H.i
            // $row[5]: Waktu Breakdown (Akhir) -> d M Y H.i or '-'
            // $row[6]: Spare (Unit)
            // $row[7]: Spare Jam Datang -> d M Y H.i or '-'
            // $row[8]: Loss time interval (calculated dynamically automatically)
            // $row[9]: % (calculated automatically)
            // $row[10]: Status (calculated automatically)
            
            $unitNomor = trim((string)($row[2] ?? ''));
            $vendorName = trim((string)($row[1] ?? ''));
            
            if (!$unitNomor || !$vendorName) {
                $this->skippedCount++;
                $this->skippedReasons[] = "Baris Kosong / Tanpa Unit & Vendor";
                continue; // Skip silently if core identifiers are blank
            }

            // Bind explicitly to Vendor (Defaults to null if missing or invalid, no longer rejects)
            $vendor = Vendor::where('nama_vendor', $vendorName)->first();
            $vendorId = $vendor ? $vendor->id : null;

            // Bind master unit forcefully
            $unit = MasterUnit::where('nomor_lambung', $unitNomor)->first();
            if (!$unit) {
                $this->skippedCount++;
                $this->skippedReasons[] = "Unit tidak valid: $unitNomor";
                continue; 
            }

            $waktuAwalStr = trim((string)($row[4] ?? ''));
            if (!$waktuAwalStr) {
                $this->skippedCount++;
                $this->skippedReasons[] = "Waktu Awal kosong untuk unit: $unitNomor";
                continue; 
            }

            try {
                $waktuAwal = $this->parseDate($waktuAwalStr);
                if (!$waktuAwal) {
                    $this->skippedCount++;
                    $this->skippedReasons[] = "Format Waktu Awal gagal di-parsing: $waktuAwalStr";
                    continue;
                }

                $waktuAkhirStr = trim((string)($row[5] ?? '-'));
                $waktuAkhir = ($waktuAkhirStr !== '-' && $waktuAkhirStr !== '') ? $this->parseDate($waktuAkhirStr) : null;

                $waktuDatangStr = trim((string)($row[7] ?? '-'));
                $waktuDatang = ($waktuDatangStr !== '-' && $waktuDatangStr !== '') ? $this->parseDate($waktuDatangStr) : null;

                $spareUnitNomor = trim((string)($row[6] ?? '-'));
                $spareUnitId = null;
                if ($spareUnitNomor !== '-' && $spareUnitNomor !== '') {
                    // Magically create the spare unit if it doesn't exist yet, bind to the same vendor
                    $spareUnit = MasterUnit::firstOrCreate(
                        ['nomor_lambung' => $spareUnitNomor],
                        [
                            'vendor_id' => $vendorId,
                            'jenis_unit' => 'Auto-Generated (Import Spare)'
                        ]
                    );
                    $spareUnitId = $spareUnit->id;
                }

                $keterangan = trim((string)($row[3] ?? ''));

                // Intelligent Sync: If logging the same unit at the exact same start time, UPDATE instead of SKIP
                $existingLog = BreakdownLog::where('unit_id', $unit->id)
                    ->where('waktu_awal_bd', $waktuAwal)
                    ->first();
                
                if ($existingLog) {
                    $existingLog->update([
                        'waktu_akhir_bd' => $waktuAkhir,
                        'spare_unit_id' => $spareUnitId,
                        'waktu_spare_datang' => $waktuDatang,
                        'keterangan' => $keterangan,
                    ]);
                    $this->updatedCount++;
                    continue; // Row was successfully synced, move to next
                }

                BreakdownLog::create([
                    'unit_id' => $unit->id,
                    'vendor_id' => $vendorId, 
                    'user_id' => auth()->id() ?? 1,
                    'waktu_awal_bd' => $waktuAwal,
                    'waktu_akhir_bd' => $waktuAkhir,
                    'spare_unit_id' => $spareUnitId,
                    'waktu_spare_datang' => $waktuDatang,
                    'keterangan' => $keterangan,
                ]);

                $this->importedCount++;

            } catch (\Exception $e) {
                $this->skippedCount++;
                $this->skippedReasons[] = "System Exception: " . $e->getMessage();
                Log::error("Excel Import Crash on Row: " . $e->getMessage() . " Data: " . json_encode($row));
                continue;
            }
        }
    }

    /**
     * Safely transpile Excel's variant proprietary date payloads or pure strings into eloquent Carbons
     */
    private function parseDate($value)
    {
        if (empty($value)) return null;

        // Maatwebsite raw native numeric representation
        if (is_numeric($value)) {
            return Carbon::instance(\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($value));
        }
        
        try {
            // Translate the "d M Y H.i" legacy export format output (e.g. 24 Mar 2026 14.30)
            $str = str_replace('.', ':', $value);
            return Carbon::createFromFormat('d M Y H:i', $str);
        } catch (\Exception $e) {
            try {
                // Final standard explicit fallback
                return Carbon::parse($value);
            } catch (\Exception $e2) {
                return null;
            }
        }
    }
}
